sonar.projectKey=Andryss_ToDoOps_e696790b-db9e-47ca-8c63-e84da8758445

sonar.sources=src

sonar.tests=src

sonar.test.inclusions=**/*.test.tsx,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/build/**
