# Copy to vars.yml and set your values. Do not commit vars.yml.

# todoops-app-vm public IP (terraform: terraform output -raw todoops_app_vm_public_ip)
todoops_app_vm_ip: "10.0.0.1"

# SSH user on the VM
ansible_user: ubuntu

# Path to SSH private key
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
